version: "3.8"
services:
  bind:
    restart: always
    image: chadhutchins182/docker-bind-rpi
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
    - /srv/docker/bind:/data
