version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Enabling qemu
          command: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run:
          name: Building arm based image.
          command: docker build -t docker-bind-rpi .
      - run:
          name: Listing built images
          command: docker images
      - run:
          name: Running arm based image.
          command: docker run --rm docker-bind-rpi